### ISSUE TITLE
No more than 14 tracks

### ISSUE THREAD

**Issue by nobef** [AppTesterMC/youtube-playlist.lua#1]
Great idea and execution, but does not show more than 14 pieces in the playlist. It's cool that jam also works if you take the ID and create a sheet using append_yt_pl_feed.lua. For example I created m3u8 of this jam https://www.youtube.com/watch?v=hnpILIIo9ek&list=RDhnpILIIo9ek
  Here is the file: 
[youtubetest.m3u8.txt](https://github.com/AppTesterMC/youtube-playlist.lua/files/11312943/youtubetest.m3u8.txt)
![изображение](https://user-images.githubusercontent.com/77186394/234068735-920c11c8-296d-4a3c-b47a-3b917b41b837.png)
Well, here she showed 15

**Comment by AppTesterMC** [comment]
Thanks for the feedback @jezokshe ! Yes that is the intended behavior. Last/top 15 items are added to the m3u8 as this is based on the special [media RSS](https://www.rssboard.org/media-rss) provided by [youtube](https://web.archive.org/web/20111111013544/https://code.google.com/intl/en/apis/youtube/2.0/reference.html#API_Request_XML_Element_Definitions).
Check the xml response (it only contains 15 entries):

[https://www.youtube.com/feeds/videos.xml?playlist_id=RDhnpILIIo9ek](https://www.youtube.com/feeds/videos.xml?playlist_id=RDhnpILIIo9ek)

To be able to access the whole playlist either a api key is needed or a scrapping of the webpage source of the playlist which complicates the things. so to keep it simple I made this approach.
